In [1]:
import numpy as np

In [19]:
a = np.array([1,2,3,4])
b = np.array([[1+3j,2,3],[3,4+.4j,5]], dtype=complex)
b

array([[1.+3.j , 2.+0.j , 3.+0.j ],
       [3.+0.j , 4.+0.4j, 5.+0.j ]])

In [30]:
c = np.array([[1,2,3],[2,3,4]])
# c[1][0]
# c.shape
# c[1,2]
# c[:,2]
# c[:][2] -> error
# c[:]

array([[1, 2, 3],
       [2, 3, 4]])

In [35]:
a = [1,2,3]
b = [4,5,6]
print(a+b)
print(np.array(a) + np.array(b))
np.arange(102)

[1, 2, 3, 4, 5, 6]
[5 7 9]


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101])

In [38]:
np.array([[[],[]],[[],[]],[[],[]]]).ndim

3

In [44]:
np.arange(12).reshape(3,2,-1)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [45]:
aa = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
aa.shape


(6, 2)

In [54]:
# aa.reshape(3,4)
bb = np.reshape(aa, (3,4))

In [55]:
# aa.reshape(3,4,'f')
np.reshape(aa,(3,4), 'f')


array([[ 1,  7,  2,  8],
       [ 3,  9,  4, 10],
       [ 5, 11,  6, 12]])

In [59]:
print(bb)
bb.sum(axis=0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([15, 18, 21, 24])

In [61]:
c = np.arange(16).reshape(4,4)

In [64]:
print(c)
# print()
mask = (c%3 == 0)
print(mask)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True False False  True]
 [False False  True False]
 [False  True False False]
 [ True False False  True]]


In [66]:
c[mask]
c[ c%2==0 ]

array([ 0,  2,  4,  6,  8, 10, 12, 14])